<?php

namespace ContainerR9bZwGW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTask2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.O6OaqSf.App\Entity\Task' shared service.
     *
     * @return \App\Entity\Task
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.O6OaqSf": it needs an instance of "App\\Entity\\Task" but this type has been excluded in "config/services.yaml".');
    }
}
